image: python:latest

stages:
  - test
  - deploy

test-all:
  stage: test
  script:
    - make
    - make tests
    - make clean

deploy-pypi:
  stage: deploy
  when: manual
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install wheel 
    - pip install twine 
    - python README.md.py README.md
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

