image: python:latest

stages:
  - test
  - deploy

test-all:
  stage: test
  script:
    - make
    - make tests
    - make clean

deploy-pypi:
  stage: deploy
  when: manual
  script:
    - pip install wheel 
    - pip install twine 
    - python setup.py sdist bdist_wheel
    # upload

